### ISSUE TITLE
How to add custom header key in useEventSource?

### ISSUE THREAD

**Issue by esmadrider** [Lusito/react-nano#1]
Hi, I'm trying to use [chaiNNer](https://github.com/chaiNNer-org/chaiNNer/tree/main) to build a workflow app, which uses react-nano to make the EventSource API call.

Now I want to add a custom header in the API call, how can I do it?

I know the [EventSource API - MDN Page](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) doesn't support a way of injecting the header key, but I also found [event-source-polyfill](https://www.npmjs.com/package/event-source-polyfill) can do it by another way.

I'm not so good to merge the `event-source-polyfill` header injection function into `@react-nano/use-event-source`.

Can this repo support header key injection more than the official EventSource API?

Which I wish:

```
export const useBackendEventSource = (): readonly [BackendEventSource | null, EventSourceStatus] => {
    return useEventSource(`${REACT_APP_ENV}/sse`, true, {
      headers: { AAA: 1 }
    });
};
```

See also: https://github.com/chaiNNer-org/chaiNNer/issues/1798

**Comment by Lusito** [comment]
Seems there is a working solution for now in the other topic. Give me some time to think about a better solution.

**Comment by Lusito** [comment]
So, I've given this a closer look:

## What I could do (but won't)
From a TypeScript perspective, I could easily do this with a major version bump (since it's a breaking change):
```ts
function useEventSource<T extends EventSourceInit>(
    url: string,
    options?: T,
    ESClass: EventSourceConstructor<T> = EventSource
) {
```

Which would allow this syntax:
```ts
 return useEventSource(`${REACT_APP_ENV}/sse`, {
      withCredentials: true,
      headers: { AAA: 1 }
    }, EventSourcePolyFill);
```

**However**, from a runtime/react perspective, this comes with a flaw:
Every render of the component would pass a new options instance. Which would cause a reconnect, when I use the options in the dependencies array of useEffect. So the only way to avoid this, would be to pass a dependencies array:

```ts
 return useEventSource(`${REACT_APP_ENV}/sse`, {
      withCredentials: true,
      headers: { AAA: 1 }
    }, [/* anything that changes the options content */], EventSourcePolyFill);
```

With 4 parameters, useEventSource becomes harder to understand and I might even tend to make it accept an options param instead:

```ts
  return useEventSource(`${REACT_APP_ENV}/sse`, {
    init: {
      withCredentials: true,
      headers: { AAA: 1 },
    },
    dependencies: [
      /* anything that changes the options content */
    ],
    ESClass: EventSourcePolyFill,
  });
```

Both approaches would make the usage of the hook somewhat ugly and I am not sure it's so much better than the approach suggested by @RunDevelopment.

**Final thoughts** (unless you have a better idea):

## 1. **Most preferable** would be..
if you don't do headers at all, since the EventSource standard does not support it. Only the polyfill does.

I am aware, that this is not always an option (I had to use the polyfill for exactly this reason in a commercial project), but if you can solve it via cookies, you save yourself a lot of trouble, as you don't need to pass this data through your code. Using `withCredentials: true` is all you need.

Most likely the reason you are using a header is, because you have your auth-token in the frontend. This has many disadvantages:
- You need to have a lot more code in the frontend for handling authorization
- You need a way to invalidate or refresh the token in the frontend as well
- You need to pass down the authorization header both to the event source and all other requests.

Instead, let the backend or BFF handle the authorization, invalidation and token refresh and only store a session-id in the frontend.

## 2. If you absolutely have to use headers..
.. you'll need to use the polyfill and in that case, it seems cleaner to use the override approach.

This is how I would rewrite @RunDevelopment's solution, adjusted to  @hylerrix's example:
```ts
function createESClassWithHeaders(headers: HeadersInit): EventSourceConstructor {
    return class ESClass extends EventSourcePolyfill {
        constructor(url: string, options?: EventSourceInit) {
            super(url, { ...options, headers });
        }
    };
}

export const useBackendEventSource = (
    port: number
): readonly [BackendEventSource | null, EventSourceStatus] => {
    const aaaHeader = useAaaHeader(); // or however you get to your header
    const ESClass = useMemo(() => createESClassWithHeaders({ AAA: aaaHeader }), [aaaHeader]);

    return useEventSource(`http://localhost:${port}/sse`, true, ESClass);
}
```

This looks a lot cleaner to me than anything I could rewrite the API of useEventSource to.

This is less work than approach 1, but trust me, making the backend handle cookies instead is well worth the investment.

Feel free to give other suggestions.

**Comment by esmadrider** [comment]
Thx, it helps me a lot! The only different change is about the type `HeadersInit`.

```
type HeadersInit = [string, string][] | Record<string, string> | Headers
```

Due to the `interface EventSourcePolyfillInit` only needing headers with type `{ [name: string]: string }`, it should be like this:

```
const createESClassWithHeaders = (headers: { [name: string]: string }): EventSourceConstructor => {
    return class ESClass extends EventSourcePolyfill {
        constructor(url: string, options?: EventSourceInit) {
            super(url, { ...options, headers });
        }
    };
}

export const useBackendEventSource = (): readonly [BackendEventSource | null, EventSourceStatus] => {
    const ESClass = useMemo(() => createESClassWithHeaders({ 'AAA': 1, }), []);
    return useEventSource(`${REACT_APP_ENV}/sse`, true, ESClass);
};
```

It worked for me now.

**Comment by esmadrider** [comment]
I'm feeling good and want to make a pull request to [@react-nano/use-event-source](https://github.com/Lusito/react-nano/blob/3efa0ac8503688c2796a19504e07dd57eef2da18/packages/use-event-source/src/index.ts#L3), and add a function called `useEventSourceWithHeaders`.

Is it OK? I'll make a pull request later and the chosen whether to be merged is up to you. Thx! 

## PLUS

> This is less work than approach 1, but trust me, making the backend handle cookies instead is well worth the investment.

Thx for the alert. In the chaiNNer-like app we build, cookies are not a good solution. Reason can be seen in https://github.com/chaiNNer-org/chaiNNer/issues/1798#issuecomment-1549218052.

**Comment by Lusito** [comment]
> Due to the `interface EventSourcePolyfillInit` only needing headers with type `{ [name: string]: string }`, it should be like this:

I looked at the source code: https://github.com/Yaffle/EventSource/blob/master/src/eventsource.js
From what I can tell, it uses normal fetch under the hood. Fetch receives HeadersInit. But if you don't care about those possibilities, sure you can ignore them.

I'll take a look at the PR.

**Comment by esmadrider** [comment]
The pull request https://github.com/Lusito/react-nano/pull/2 is closed now (reason listed in there).

I have no other questions. https://github.com/chaiNNer-org/chaiNNer/issues/1798#issuecomment-1550042833 is a good suggestion. Just in the EventSource request, I passed data via get parameters.

Feel free to close this issue and thanks for all your comment and sharing.
